language: python
python:
  - 2.7

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - make version=$TRAVIS_PYTHON_VERSION .installed.cfg

script:
  - make tests

notifications:
  irc:
    - "#kreativkombinat"
