# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           ./app
destination:      ./_site
layouts_dir:      ./_layouts
exclude:          [".editorconfig", ".gitignore", ".bowerrc", "jshintrc", "bower.json", "config.json", "Gruntfile.js", "gulpfile.babel.js", "package.json", "manifest.cfg", "rules.xml", "node_modules", "bower_components", "README.md", "assets", "less", "dist", "js", "overrides", "docs", "templates", "Makefile", "sass"]
port:             9001

# Custom vars
current_version:  1.0.0
repo:             https://github.com/ade25/
